; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = uno

[env]
build_flags =
    -Wall
    -I include
lib_deps = 
    bakercp/PacketSerial@^1.4.0
lib_extra_dirs =
    ./lib/components
    ./lib/devices
    ./lib/platform/common
extra_scripts = 
    pre:scripts/preBuild.py 
    
; Connect to gdb server
debug_build_flags = -g
debug_tool = custom
debug_port = :1234

[atmelavr]
build_flags =
    ${env.build_flags}
;    -Wl,--undefined=_mmcu,--section-start=.mmcu=0x910000
lib_deps = 
    ${env.lib_deps}
       felias-fogg/SoftI2CMaster@^2.1.3
lib_extra_dirs =
    ${env.lib_extra_dirs}
    ./lib/platform/arch/atmelavr
build_src_filter =
    ${env.build_src_filter}
    +<../lib/platform/arch/atmelavr/avr_mcu_section>

[esp32]
build_flags = 
    -D ARDUINO_ESP32
build_src_flags = -include include/esp32_arduino_framework_patch.h
lib_extra_dirs =
    ./lib/platform/arch/esp32

[rp2040]
build_flags =
    ${env.build_flags}
    -D ARDUINO_ARCH_RP2040
    -I lib/platform/common/hal
    -I lib/platform/common/shield
    -I lib/platform/common/packetSerial
    -I lib/platform/arch/rp2040/platform
    -I lib/platform/arch/rp2040/i2c
lib_extra_dirs =
    ./lib/components
    ./lib/devices
    ./lib/platform/arch/rp2040/platform
    ./lib/platform/arch/rp2040/i2c
build_src_filter =
    ${env.build_src_filter}
    +<../lib/platform/common/packetSerial>
    +<../lib/platform/common/shield>

[env:uno]
framework = arduino
platform = atmelavr
board = uno

build_flags = ${atmelavr.build_flags}
lib_deps = ${atmelavr.lib_deps} 
lib_extra_dirs = ${atmelavr.lib_extra_dirs}
build_src_filter = ${atmelavr.build_src_filter}

[env:mega2560]
framework = arduino
platform = atmelavr
board = megaatmega2560

build_flags = ${atmelavr.build_flags}
lib_deps = ${atmelavr.lib_deps} 
lib_extra_dirs = ${atmelavr.lib_extra_dirs}
build_src_filter = ${atmelavr.build_src_filter}
    
[env:uno_r4_wifi]
framework = arduino
platform = renesas-ra
board = uno_r4_wifi

build_flags =
    ${env.build_flags}
    -D ARDUINO_ARCH_RENESAS
lib_extra_dirs =
    ${env.lib_extra_dirs}
    ./lib/platform/arch/renesas-ra

[env:ESP32-S3-DevKitC-1]
framework = arduino
platform = espressif32
board = esp32-s3-devkitc-1
build_flags = 
    ${env.build_flags}
    ${esp32.build_flags}
lib_extra_dirs = 
    ${esp32.lib_extra_dirs}
    ${env.lib_extra_dirs}
lib_deps = 
    ${env.lib_deps}
    adafruit/Adafruit NeoPixel@^1.12.0

[env:esp32-s3-mini-1] //this is for the official AYAB board and is included for long term support and compatibility
framework = arduino
platform = espressif32
board = esp32-s3-devkitm-1
build_flags = 
    ${env.build_flags}
    ${esp32.build_flags}
    -D PIO_DISABLE_PSRAM
lib_extra_dirs = 
    ${esp32.lib_extra_dirs}
    ${env.lib_extra_dirs}

board_build.flash_size = 4MB

[env:rpipicow]
framework = arduino
platform = raspberrypi
board = pico
build_flags = ${rp2040.build_flags}
lib_deps = ${env.lib_deps}
lib_extra_dirs = ${rp2040.lib_extra_dirs}
upload_protocol = picotool
board_build.filesystem_size = 0.5m

[env:native]
platform = native
test_framework = googletest
