// Auto-generated from lib/platform/common/pin_definitions.json
// Do not edit this file directly
// Environment: rpipicow

#ifndef PIN_DEFINITIONS_H
#define PIN_DEFINITIONS_H

#include <stdint.h>

constexpr uint8_t PIEZO_PIN = 10U;
constexpr uint8_t ENC_A_PIN = 6U;
constexpr uint8_t ENC_B_PIN = 5U;
constexpr uint8_t ENC_C_PIN = 7U;
constexpr uint8_t MCP_SDA_PIN = 8U;
constexpr uint8_t MCP_SCL_PIN = 9U;
constexpr uint8_t EOL_PIN_R_N = 15U;
constexpr uint8_t EOL_PIN_R_S = 14U;
constexpr uint8_t EOL_PIN_L_N = 13U;
constexpr uint8_t EOL_PIN_L_S = 12U;
constexpr uint8_t EOL_R_PIN = 15U;
constexpr uint8_t EOL_L_PIN = 13U;

#endif // PIN_DEFINITIONS_H
