// Auto-generated from lib/platform/common/pin_definitions.json
// Do not edit this file directly
// Environment: ESP32-S3-DevKitC-1

#ifndef PIN_DEFINITIONS_H
#define PIN_DEFINITIONS_H

#include <stdint.h>

#define USE_WS2812_STATUS_LED

constexpr uint8_t PIEZO_PIN = 16U;
constexpr uint8_t ENC_A_PIN = 3U;
constexpr uint8_t ENC_B_PIN = 46U;
constexpr uint8_t ENC_C_PIN = 8U;
constexpr uint8_t MCP23017_ADDR_0 = 0U;
constexpr uint8_t MCP_SDA_PIN = 17U;
constexpr uint8_t MCP_SCL_PIN = 18U;
constexpr uint8_t WS2812_DATA_PIN = 48U;
constexpr uint8_t EOL_PIN_R_N = 5U;
constexpr uint8_t EOL_PIN_R_S = 4U;
constexpr uint8_t EOL_PIN_L_N = 7U;
constexpr uint8_t EOL_PIN_L_S = 6U;
constexpr uint8_t EOL_R_PIN = 5U;
constexpr uint8_t EOL_L_PIN = 7U;

#endif // PIN_DEFINITIONS_H
