// Auto-generated from lib/platform/common/pin_definitions.json
// Do not edit this file directly
// Environment: uno

#ifndef PIN_DEFINITIONS_H
#define PIN_DEFINITIONS_H

#include <stdint.h>

constexpr uint8_t I2C_HARDWARE = 1U;
constexpr uint8_t LED_A_PIN = 5U;
constexpr uint8_t LED_B_PIN = 6U;
constexpr uint8_t PIEZO_PIN = 9U;
constexpr uint8_t ENC_A_PIN = 2U;
constexpr uint8_t ENC_B_PIN = 3U;
constexpr uint8_t ENC_C_PIN = 4U;
#define SDA_PORT PORTC
constexpr uint8_t SDA_PIN = 4U;
#define SCL_PORT PORTC
constexpr uint8_t SCL_PIN = 5U;
constexpr uint8_t EOL_R_PIN = 14U;
constexpr uint8_t EOL_L_PIN = 15U;
constexpr uint8_t EOL_R_L_PIN = 7U;
constexpr uint8_t EOL_R_DETECT_PIN = 8U;
constexpr uint8_t EOL_PIN_R_N = 14U;
constexpr uint8_t EOL_PIN_R_S = 15U;
constexpr uint8_t EOL_PIN_L_N = 15U;
constexpr uint8_t EOL_PIN_L_S = 14U;

#endif // PIN_DEFINITIONS_H
